# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitdeck" do
  name "gitdeck"
  desc "Terminal UI for monitoring CI/CD pipelines."
  homepage "https://github.com/waabox/gitdeck"
  version "1.2.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gitdeck"

  on_macos do
    on_intel do
      url "https://github.com/waabox/gitdeck/releases/download/v#{version}/gitdeck_darwin_amd64.tar.gz"
      sha256 "0fe3c4f9e733d7e018f865d3872c5455179932adf4f51d844c163a40896fce7e"
    end
    on_arm do
      url "https://github.com/waabox/gitdeck/releases/download/v#{version}/gitdeck_darwin_arm64.tar.gz"
      sha256 "4e439eaf4689fc92bba98b5fcf83e5346b21a83fd32af4d350b9b1f69008c68c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/waabox/gitdeck/releases/download/v#{version}/gitdeck_linux_amd64.tar.gz"
      sha256 "f7d534ad5f424d6a0a4a6347d104ddc3cce4bad9a6075c86d5898b61553c6e2d"
    end
    on_arm do
      url "https://github.com/waabox/gitdeck/releases/download/v#{version}/gitdeck_linux_arm64.tar.gz"
      sha256 "c187d06a35dee2b000340b8bb71bbcf9be03b8b5209378a2609190f82418f869"
    end
  end

  caveats do
    "Run gitdeck from inside any git repository."
  end

  # No zap stanza required
end
