# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitdeck" do
  name "gitdeck"
  desc "Terminal UI for monitoring CI/CD pipelines."
  homepage "https://github.com/waabox/gitdeck"
  version "1.4.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gitdeck"

  on_macos do
    on_intel do
      url "https://github.com/waabox/gitdeck/releases/download/v#{version}/gitdeck_darwin_amd64.tar.gz"
      sha256 "ce5f16750773eaaffa4d53c4752c9d3eaea6d8b4813f5580ded6fdeddc0e5801"
    end
    on_arm do
      url "https://github.com/waabox/gitdeck/releases/download/v#{version}/gitdeck_darwin_arm64.tar.gz"
      sha256 "85d31bd16d7df82d0666a3848dfaacab55230d3bdbbd2006635ec3dc787c9051"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/waabox/gitdeck/releases/download/v#{version}/gitdeck_linux_amd64.tar.gz"
      sha256 "436ff29da0173bfdf630566286559ffb415d70176bfc35db63edfe0463af1022"
    end
    on_arm do
      url "https://github.com/waabox/gitdeck/releases/download/v#{version}/gitdeck_linux_arm64.tar.gz"
      sha256 "c361fc42e14eaf51a75719ba75523f6c0165ddd1527b28f5ab1f3b0d0e830393"
    end
  end

  caveats do
    "Run gitdeck from inside any git repository."
  end

  # No zap stanza required
end
