# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitdeck" do
  name "gitdeck"
  desc "Terminal UI for monitoring CI/CD pipelines."
  homepage "https://github.com/waabox/gitdeck"
  version "1.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gitdeck"

  on_macos do
    on_intel do
      url "https://github.com/waabox/gitdeck/releases/download/v#{version}/gitdeck_darwin_amd64.tar.gz"
      sha256 "486c30ae0465ed1aad6e8169a9c04f48bafac9dcad319222384bbca74646f3d5"
    end
    on_arm do
      url "https://github.com/waabox/gitdeck/releases/download/v#{version}/gitdeck_darwin_arm64.tar.gz"
      sha256 "4d65497e5cbfa3337fdaa7e55f85d2ee46e1f3879815d73178dde62b59b40e7b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/waabox/gitdeck/releases/download/v#{version}/gitdeck_linux_amd64.tar.gz"
      sha256 "425fa258321ee02005f67603f6e987ad802d03076722f382cd7b308586843a81"
    end
    on_arm do
      url "https://github.com/waabox/gitdeck/releases/download/v#{version}/gitdeck_linux_arm64.tar.gz"
      sha256 "d4ab8e3d610c712a01ef976dc12db3d535ba84392de87402360d9c15001edd19"
    end
  end

  caveats do
    "Run gitdeck from inside any git repository."
  end

  # No zap stanza required
end
